if( APPLE )
	find_program( MACDEPLOYQT_EXECUTABLE macdeployqt HINTS "${_qt_bin_dir}" )

	set( BUNDLE_PATH "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.bundle" )

	add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD
		COMMAND ${CMAKE_COMMAND} -D MACDEPLOYQT_EXECUTABLE=${MACDEPLOYQT_EXECUTABLE} -D BUNDLE_PATH=${BUNDLE_PATH} -D PROJECT_NAME=${PROJECT_NAME} -P ${CMAKE_SOURCE_DIR}/cmake/MacFixBundlePostBuild.cmake
		VERBATIM
		)
endif( APPLE )

