#!/bin/sh

echo "Fugio Homebrew Installer"

if [ ! -x /usr/local/bin/brew ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

taps=$(/usr/local/bin/brew tap)

echo $taps

if ! echo "$taps" | grep -q 'homebrew/science' &> /dev/null; then
  echo "Adding tap homebrew/science..."
  brew tap homebrew/science
fi

if ! echo "$taps" | grep -q 'homebrew/versions' &> /dev/null; then
  echo "Adding tap homebrew/versions..."
  brew tap homebrew/versions
fi

if [ ! -e /usr/local/opt/portaudio ]; then
  brew install portaudio
else
  echo "portaudio is already installed..."
fi

if [ ! -e /usr/local/opt/lua ]; then
  brew install lua
else
  echo "lua is already installed..."
fi

if [ ! -e /usr/local/opt/portmidi ]; then
  brew install portmidi
else
  echo "portmidi is already installed..."
fi

if [ ! -e /usr/local/opt/fftw ]; then
  brew install fftw
else
  echo "fftw is already installed..."
fi

if [ ! -e /usr/local/opt/dlib ]; then
  brew install homebrew/science/dlib
else
  echo "dlib is already installed..."
fi

if [ ! -e /usr/local/opt/glew ]; then
  brew install glew
else
  echo "glew is already installed..."
fi

if [ ! -e /usr/local/opt/opencv3 ]; then
  brew install homebrew/science/opencv3
else
  echo "fftw is already installed..."
fi

if [ ! -e /usr/local/opt/snappy ]; then
  brew install snappy
else
  echo "snappy is already installed..."
fi

if [ ! -e /usr/local/opt/ffmpeg ]; then
  brew install ffmpeg --with-fdk-aac --with-libass --with-x265 --with-freetype --with-libvorbis --with-libvpx --with-opus
else
  echo "ffmpeg is already installed..."
fi

if [ ! -e /Applications/Fugio ]; then
  brew cask install Fugio
else
  echo "Fugio is already installed..."
fi

brew update
brew upgrade

