#!/bin/sh

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew tap homebrew/science
brew tap homebrew/versions

brew install lua fftw portaudio portmidi

brew update
brew upgrade
