#!/bin/sh

cat << EOM
FFFFFFFFFFFFFFFFFFFFFF                                        iiii
F::::::::::::::::::::F                                       i::::i
F::::::::::::::::::::F                                        iiii
FF::::::FFFFFFFFF::::F
  F:::::F       FFFFFFuuuuuu    uuuuuu     ggggggggg   gggggiiiiiii    ooooooooooo
  F:::::F             u::::u    u::::u    g:::::::::ggg::::gi:::::i  oo:::::::::::oo
  F::::::FFFFFFFFFF   u::::u    u::::u   g:::::::::::::::::g i::::i o:::::::::::::::o
  F:::::::::::::::F   u::::u    u::::u  g::::::ggggg::::::gg i::::i o:::::ooooo:::::o
  F:::::::::::::::F   u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F::::::FFFFFFFFFF   u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F:::::F             u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F:::::F             u:::::uuuu:::::u  g::::::g    g:::::g  i::::i o::::o     o::::o
FF:::::::FF           u:::::::::::::::uug:::::::ggggg:::::g i::::::io:::::ooooo:::::o
F::::::::FF            u:::::::::::::::u g::::::::::::::::g i::::::io:::::::::::::::o
F::::::::FF             uu::::::::uu:::u  gg::::::::::::::g i::::::i oo:::::::::::oo
FFFFFFFFFFF               uuuuuuuu  uuuu    gggggggg::::::g iiiiiiii   ooooooooooo
                                                    g:::::g
                                        gggggg      g:::::g
                                        g:::::gg   gg:::::g
                                         g::::::ggg:::::::g
                                          gg:::::::::::::g
                                             ggg::::::ggg
                                                gggggg
EOM

while true; do
	read -p "Do you wish to install Fugio? (Y/N) " yn
	case $yn in
		[Yy]* ) break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
	esac
done

if [ ! -x /usr/bin/gcc ]; then
	xcode-select --install
fi

if [ ! -x /usr/local/bin/brew ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! echo "$taps" | grep -q 'caskroom/cask' &> /dev/null; then
  echo "Adding tap caskroom/cask..."
  brew tap caskroom/cask
fi

if [ ! -e /usr/local/opt/ffmpeg ]; then
  brew install ffmpeg --with-fdk-aac --with-libass --with-x265 --with-freetype --with-libvorbis --with-libvpx --with-opus
else
  echo "ffmpeg is already installed..."
fi

if [ ! -e /Applications/Fugio ]; then
  brew cask install fugio
else
  echo "Fugio is already installed..."
fi

brew update
brew upgrade

